### ISSUE TITLE
Unable to detect architecture

### ISSUE THREAD

**Issue by zeusofyork** [jacopotediosi/GoogleDialerMod-Magisk#1]
Get an error message not being able to detect cpu arch.

**Comment by jacopotediosi** [comment]
Uh this is interesting.
Can you share details about your phone, model, android version, magisk version?
Thanks

**Comment by zeusofyork** [comment]
Just a side note, I do have the stand alone apk installed.

OnePlus 9 pro, Android 12 OB1, magisk(canary) 23013

**Comment by zeusofyork** [comment]
Ahh, is the installer only checking for ARM32 and x86?

**Comment by jacopotediosi** [comment]
> Ahh, is the installer only checking for ARM32 and x86?

This is the line that detects the CPU architecture: https://github.com/jacopotediosi/GoogleDialerMod-Magisk/blob/a109ce24c5a5b29c9c6dad492fb7faca8f696a51/install.sh#L55.
Actually the ARCH32 variable is not documented in Magisk, which recommends using ARCH instead.
It may be that for some reason that variable is not set on your phone. I'll release a fix because it is evident that the check is currently being done poorly.

**Comment by zeusofyork** [comment]
this is what I get from a shell. 

processor       : 0
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0xd05
CPU revision    : 0

**Comment by zeusofyork** [comment]
Last comment, ended up finding I'm ARM64 script only checks for 32 and 86
![Uploading Screenshot_2021-11-11-21-27-03-86_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by jacopotediosi** [comment]
Hi @zeusofyork, can you please confirm the release 1.03 works for you?

**Comment by BRUHItsABunny** [comment]
1.03 fixes the issue for me, also tested on OnePlus 9 Pro
