### ISSUE TITLE
Not silenced notifications about recording call

### ISSUE THREAD

**Issue by morethanhater** [jacopotediosi/GoogleDialerMod-Magisk#2]
**What's working**: call recording appeared and works within unsupported region (Ukraine)
**Problem**: both of users hears "registration has started / ended" sounds - it's not silenced

**Device**: oneplus 9 pro
**Model**: LE2120
**Android**: 11 (oxygenos 11.2.9.9.LE15AA)
**Security Patch**: 2021 september (2021.09.01)
**Kernel**: stock
**Additional magisk modules**: SafetyNetFix

Also, i tried to uninstall this magisk module and install apk version
After numerous reboots, start/stop dialler app, reswitching toggles (notification toggle were failing and goes back to off) - it works now
something seems to conflict with these sqlite requests

Will provide any additional info, just let me know how to

**Comment by jacopotediosi** [comment]
Hi,
Thanks for your reporting.

This module was a tentative workaround to solve the standalone APK version bugs regarding the storage access limitations on Android >= 11. Probably the bug you talk about in this issue is one of those.

With the [latest release of the APK version](https://github.com/jacopotediosi/GoogleDialerMod/releases/latest) I finally solved those bugs, so this repository will be deprecated and archived.

From now on, please use only the [APK standalone version](https://github.com/jacopotediosi/GoogleDialerMod).

If you find your bug persists also in the APK standalone version, please report them [there](https://github.com/jacopotediosi/GoogleDialerMod/issues).
